name: Auto-WP Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Run dry test
      run: |
        chmod +x auto-wp.sh
        ./auto-wp.sh wp-test-ci 8089
        ./auto-wp.sh --delete wp-test-ci
